### ISSUE TITLE
Please create GitHub Release 1.0.0

### ISSUE THREAD

**Issue by favoyang** [JimTheKiwifruit/SimpleSingleton#1]
@JimTheKiwifruit Thanks for making the simple but useful package. Could you please create a GitHub release 1.0.0? So it can be processed by [OpenUPM platform](https://openupm.com/packages/com.jimthekiwifruit.simplesingleton/) or UPMGitExtension.

**Comment by JimTheKiwifruit** [comment]
Good idea @favoyang :) Should have done that when I publish the repo.

**Comment by favoyang** [comment]
https://openupm.com/packages/com.jimthekiwifruit.simplesingleton/

Thanks, it’s been processed correct.
